kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-data-volume
  labels:
    app: sonar
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 1Gi
