apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-jenkins-storage-nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 15Gi
