apiVersion: v1
kind: Template
metadata:
  name: ace-app
  labels:
    app: ace-app
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ace-app
    labels:
      app: ace-app    
  spec:
    type: NodePort
    ports:
    - port: 7600
      targetPort: 7600
      protocol: TCP
      name: webui
    - port: 7800
      targetPort: 7800
      protocol: TCP
      name: ace-http
    - port: 7843
      targetPort: 7843
      protocol: TCP
      name: ace-https
    selector:
      app: "ace-app"
- apiVersion: apps/v1
  kind: Route
  apiVersion: v1
  metadata:
    name: ace-app
    labels:
      app: ace-app
    name: ace-app
  spec:
    host: ace-app.apps.nonprod.icicibankltd.com
    to:
      kind: Service
      name: ace-app

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ace-app
    labels:
      app: ace-app      
  spec:
    replicas: 1
    template:
      metadata:
        name: ace-app
        labels:
          app: ace-app
      spec:
        containers:
          - name: ace-app
            image: registry.ixpress.icicibank.com:5000/aceapp
            ports:
              - containerPort: 7600
                name: webui
              - containerPort: 7800
                name: ace-http
              - containerPort: 7843
                name: ace-https
            env:
              - name: LICENSE
                value: "accept"
              - name: USE_QMGR
                value: "false"
              - name: ACE_SERVER_NAME
                value: "ACESERVER"
              - name: SERVICE_NAME
                value: ace-app
              - name: LOG_FORMAT
                value: "json"
              - name: ACE_ENABLE_METRICS
                value: "true"
              - name: MQ_QMGR_NAME
                value: "AMQ7048E"
            volumeMounts:
              - name: webusers
                mountPath: "/home/aceuser/initial-config/webusers"
              - name: policy
                mountPath: "/home/aceuser/initial-config/policy"
        volumes:
          - name: webusers
            configMap:
              name: webusers              
          - name: policy
            configMap:
              name: policy 
            ServiceAccountName: ace-app
parameters:
- description: The name assigned to all of the objects defined in this template.
  displayName: Name
  name: NAME
- description: MQ_QMGR_NAME .
  displayName: QMGR NAME
  name: MQ_QMGR_NAME
  value: QMGR name
  required: true
- description: The image name .
  displayName: MQImage
  name: MQ_IMAGE
  value: Name_of_image_to_be_provided
- description: The MQ image version .
  displayName: MQImageVersion
  name: MQ_VERSION
  value: Name_of_image_to_be_provided
- description: The DOCKER_REGISTRY with port
  displayName: DockerRegistryWithPort
  name: DOCKER_REGISTRY
  value: Name_of_image_to_be_provided
- description: The Registry Namespace in Docker Registry
  displayName: RegistryNamespace
  name: REGISTY_NAMESPACE
  value: Name_of_image_to_be_provided
- description: The Log Format
  displayName: LogFormat
  name: LOG_FORMAT
  value: "basic"
- description: Memory Limit Of MQ
  displayName: MemoryLimt
  name: MEMORY_LIMIT
  value: 512Mi
- description: CPU Limit Of MQ
  displayName: CpuLimit
  name: CPU_LIMIT  
  value: 500m 	
