apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: ixc-jenkins
  name: ixc-jenkins
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: ixc-jenkins
    deploymentconfig: ixc-jenkins
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: ixc-jenkins
        deploymentconfig: ixc-jenkins
    spec:
      containers:
      - image: registry.ixpress.icicibank.com:5000/jenkins/jenkins-with-tools:latest
        imagePullPolicy: Always
        name: ixc-jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: ixc-jenkins-volume-1
        - mountPath: /var/run/docker.sock
          name: volume-dockersock
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: ibsi-xc-dev-mgmt02
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: devops-jenkins-sa
      serviceAccountName: devops-jenkins-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ixc-jenkins-volume-1
        persistentVolumeClaim:
          claimName: devops-jenkins-storage-nfs
      - hostPath:
          path: /var/run/docker.sock
          type: File
        name: volume-dockersock
  triggers:
  - type: ConfigChange
