apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ixc-jenkins-storage-nfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: managed-nfs-storage
