apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2020-07-27T09:50:02Z
  labels:
    app: nonprod-jenkins
  name: nonprod-jenkins
  namespace: non-production
  resourceVersion: "56759487"
  selfLink: /api/v1/namespaces/non-production/services/nonprod-jenkins
  uid: 8a99d101-cfee-11ea-82c0-000d3af2f6a6
spec:
  clusterIP: 172.30.236.245
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-2
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: nonprod-jenkins
    deploymentconfig: nonprod-jenkins
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
