allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:nodes
- system:masters
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'privileged allows access to all privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is the most relaxed SCC and should be used
      only for cluster administration. Grant with caution.'
  creationTimestamp: 2020-06-19T12:53:54Z
  name: privileged
  resourceVersion: "138861249"
  selfLink: /apis/security.openshift.io/v1/securitycontextconstraints/privileged
  uid: ee99c73f-b22b-11ea-badd-000d3af20c19
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:admin
- system:serviceaccount:openshift-infra:build-controller
- system:serviceaccount:openshift-node:sync
- system:serviceaccount:openshift-sdn:sdn
- system:serviceaccount:management-infra:management-admin
- system:serviceaccount:management-infra:inspector-admin
- system:serviceaccount:openshift-logging:aggregated-logging-fluentd
- ocpadmin
- system:serviceaccount:sonar:postgress
- system:serviceaccount:sonar:postgres
- system:serviceaccount:sonar:default
- system:serviceaccount:sonar:ixc-jenkins-docker
- nonprod-jenkins-docker
- system:serviceaccount:non-production:nonprod-jenkins-docker
- system:serviceaccount:devops:postgres
volumes:
- '*'
